# 📊 Análise Exploratória dos Dados do ProUni (2019-2020)

Este notebook contém a análise exploratória inicial dos dados do Programa Universidade para Todos (ProUni) para os anos de 2019 e 2020.

## 🎯 Objetivos
1. **Carregar e explorar** a estrutura dos dados
2. **Identificar** tipos de dados e possíveis inconsistências
3. **Analisar** dados faltantes
4. **Gerar** estatísticas descritivas básicas
5. **Verificar** se os datasets de diferentes anos têm a mesma estrutura
6. **Criar** visualizações iniciais para entender os padrões

## 📚 Bibliotecas

In [1]:
# Importação das bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings

# Configurações
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print("✅ Bibliotecas importadas com sucesso!")

✅ Bibliotecas importadas com sucesso!

## 📁 1. Carregamento dos Dados

In [2]:
# Caminhos para os arquivos
arquivo_2019 = '../data/raw/pda-prouni-2019.csv'
arquivo_2020 = '../data/raw/ProuniRelatorioDadosAbertos2020.csv'

# Tentativa de carregamento com diferentes encodings
def carregar_csv_seguro(caminho, nome_ano):
    encodings = ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']
    
    for encoding in encodings:
        try:
            df = pd.read_csv(caminho, encoding=encoding, sep=';')
            print(f"✅ {nome_ano}: Carregado com encoding {encoding}")
            print(f"   Shape: {df.shape}")
            return df
        except UnicodeDecodeError:
            continue
        except Exception as e:
            print(f"❌ Erro ao carregar {nome_ano} com {encoding}: {e}")
            continue
    
    # Tentativa com vírgula como separador
    for encoding in encodings:
        try:
            df = pd.read_csv(caminho, encoding=encoding, sep=',')
            print(f"✅ {nome_ano}: Carregado com encoding {encoding} e separador vírgula")
            print(f"   Shape: {df.shape}")
            return df
        except:
            continue
    
    print(f"❌ Não foi possível carregar {nome_ano}")
    return None

# Carregamento dos dados
print("🔄 Carregando dados...")
df_2019 = carregar_csv_seguro(arquivo_2019, "ProUni 2019")
df_2020 = carregar_csv_seguro(arquivo_2020, "ProUni 2020")

🔄 Carregando dados...
✅ ProUni 2019: Carregado com encoding utf-8
   Shape: (241032, 15)
✅ ProUni 2020: Carregado com encoding latin-1
   Shape: (166830, 17)

## 🔍 2. Primeira Exploração - Estrutura dos Dados

In [3]:
# Função para explorar estrutura básica
def explorar_estrutura(df, nome):
    print(f"\n{'='*50}")
    print(f"📊 ANÁLISE: {nome}")
    print(f"{'='*50}")
    
    if df is not None:
        print(f"\n📏 Dimensões: {df.shape[0]:,} linhas x {df.shape[1]} colunas")
        
        print(f"\n📋 Colunas disponíveis:")
        for i, col in enumerate(df.columns, 1):
            print(f"  {i:2d}. {col}")
        
        print(f"\n🔢 Tipos de dados:")
        print(df.dtypes.value_counts())
        
        print(f"\n👀 Primeiras 3 linhas:")
        display(df.head(3))
        
        return True
    else:
        print(f"❌ Dados não disponíveis para {nome}")
        return False

# Explorar ambos os datasets
sucesso_2019 = explorar_estrutura(df_2019, "ProUni 2019")
sucesso_2020 = explorar_estrutura(df_2020, "ProUni 2020")

==================================================
📊 ANÁLISE: ProUni 2019
==================================================

📏 Dimensões: 241,032 linhas x 15 colunas

📋 Colunas disponíveis:
   1. ANO_CONCESSAO_BOLSA
   2. CODIGO_EMEC_IES_BOLSA
   3. NOME_IES_BOLSA
   4. TIPO_BOLSA
   5. MODALIDADE_ENSINO_BOLSA
   6. NOME_CURSO_BOLSA
   7. NOME_TURNO_CURSO_BOLSA
   8. CPF_BENEFICIARIO_BOLSA
   9. SEXO_BENEFICIARIO_BOLSA
  10. RACA_BENEFICIARIO_BOLSA
  11. DT_NASCIMENTO_BENEFICIARIO
  12. BENEFICIARIO_DEFICIENTE_FISICO
  13. REGIAO_BENEFICIARIO_BOLSA
  14. SIGLA_UF_BENEFICIARIO_BOLSA
  15. MUNICIPIO_BENEFICIARIO_BOLSA

🔢 Tipos de dados:
object     13
float64     2
Name: count, dtype: int64

👀 Primeiras 3 linhas:

,ANO_CONCESSAO_BOLSA,CODIGO_EMEC_IES_BOLSA,NOME_IES_BOLSA,TIPO_BOLSA,MODALIDADE_ENSINO_BOLSA,NOME_CURSO_BOLSA,NOME_TURNO_CURSO_BOLSA,CPF_BENEFICIARIO_BOLSA,SEXO_BENEFICIARIO_BOLSA,RACA_BENEFICIARIO_BOLSA,DT_NASCIMENTO_BENEFICIARIO,BENEFICIARIO_DEFICIENTE_FISICO,REGIAO_BENEFICIARIO_BOLSA,SIGLA_UF_BENEFICIARIO_BOLSA,MUNICIPIO_BENEFICIARIO_BOLSA
0,2019.0,10.0,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,BOLSA INTEGRAL,EAD,Administração,Curso a distância,***03183970**,M,Branca,19/08/1993,N,Sul,PR,LONDRINA
1,2019.0,10.0,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,BOLSA INTEGRAL,EAD,Administração,Curso a distância,***92848904**,F,Branca,03/11/1999,N,Sul,PR,SAO JOSE DOS PINHAIS
2,2019.0,10.0,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,BOLSA INTEGRAL,EAD,Análise E Desenvolvimento De Sistemas,Curso a distância,***12457929**,M,Parda,02/04/1999,N,Sul,PR,QUATRO BARRAS

==================================================
📊 ANÁLISE: ProUni 2020
==================================================

📏 Dimensões: 166,830 linhas x 17 colunas

📋 Colunas disponíveis:
   1. ANO_CONCESSAO_BOLSA
   2. CODIGO_EMEC_IES_BOLSA
   3. NOME_IES_BOLSA
   4. MUNICIPIO
   5. CAMPUS
   6. TIPO_BOLSA
   7. MODALIDADE_ENSINO_BOLSA
   8. NOME_CURSO_BOLSA
   9. NOME_TURNO_CURSO_BOLSA
  10. CPF_BENEFICIARIO
  11. SEXO_BENEFICIARIO
  12. RACA_BENEFICIARIO
  13. DATA_NASCIMENTO
  14. BENEFICIARIO_DEFICIENTE_FISICO
  15. REGIAO_BENEFICIARIO
  16. UF_BENEFICIARIO
  17. MUNICIPIO_BENEFICIARIO

🔢 Tipos de dados:
object    15
int64      2
Name: count, dtype: int64

👀 Primeiras 3 linhas:

,ANO_CONCESSAO_BOLSA,CODIGO_EMEC_IES_BOLSA,NOME_IES_BOLSA,MUNICIPIO,CAMPUS,TIPO_BOLSA,MODALIDADE_ENSINO_BOLSA,NOME_CURSO_BOLSA,NOME_TURNO_CURSO_BOLSA,CPF_BENEFICIARIO,SEXO_BENEFICIARIO,RACA_BENEFICIARIO,DATA_NASCIMENTO,BENEFICIARIO_DEFICIENTE_FISICO,REGIAO_BENEFICIARIO,UF_BENEFICIARIO,MUNICIPIO_BENEFICIARIO
0,2020,322,UNIVERSIDADE PAULISTA,IPATINGA,IPATINGA,INTEGRAL,EAD,PEDAGOGIA,CURSO A DISTÂNCIA,991.XXX.XXX-91,F,Parda,11/08/1973,N,SUDESTE,MG,GOVERNADOR VALADARES
1,2020,163,UNIVERSIDADE ESTÁCIO DE SÁ,FORTALEZA,EAD VIA CORPVS - CE,INTEGRAL,EAD,MARKETING,CURSO A DISTÂNCIA,067.XXX.XXX-01,M,Parda,13/05/1987,N,NORDESTE,CE,FORTALEZA
2,2020,17670,FACULDADE DE QUIXERAMOBIM,QUIXERAMOBIM,FACULDADE DE QUIXERAMOBIM - UNIQ,INTEGRAL,PRESENCIAL,FARMÁCIA,NOTURNO,623.XXX.XXX-27,M,Parda,23/07/2001,N,NORDESTE,CE,MOMBACA

## 🔎 3. Comparação da Estrutura entre Anos

In [4]:
# Comparar estruturas se ambos os datasets foram carregados
if sucesso_2019 and sucesso_2020:
    print("🔄 Comparando estruturas dos datasets...\n")
    
    # Comparar colunas
    cols_2019 = set(df_2019.columns)
    cols_2020 = set(df_2020.columns)
    
    cols_comuns = cols_2019.intersection(cols_2020)
    cols_apenas_2019 = cols_2019 - cols_2020
    cols_apenas_2020 = cols_2020 - cols_2019
    
    print(f"📊 Resumo da Comparação:")
    print(f"  • Colunas em comum: {len(cols_comuns)}")
    print(f"  • Apenas em 2019: {len(cols_apenas_2019)}")
    print(f"  • Apenas em 2020: {len(cols_apenas_2020)}")
    
    if cols_apenas_2019:
        print(f"\n🔹 Colunas apenas em 2019:")
        for col in sorted(cols_apenas_2019):
            print(f"  • {col}")
    
    if cols_apenas_2020:
        print(f"\n🔹 Colunas apenas em 2020:")
        for col in sorted(cols_apenas_2020):
            print(f"  • {col}")
    
    print(f"\n✅ Colunas comuns: {len(cols_comuns)}")
    for col in sorted(cols_comuns):
        print(f"  • {col}")
else:
    print("❌ Não é possível comparar - algum dataset não foi carregado")

🔄 Comparando estruturas dos datasets...

📊 Resumo da Comparação:
  • Colunas em comum: 8
  • Apenas em 2019: 7
  • Apenas em 2020: 9

🔹 Colunas apenas em 2019:
  • CPF_BENEFICIARIO_BOLSA
  • DT_NASCIMENTO_BENEFICIARIO
  • MUNICIPIO_BENEFICIARIO_BOLSA
  • RACA_BENEFICIARIO_BOLSA
  • REGIAO_BENEFICIARIO_BOLSA
  • SEXO_BENEFICIARIO_BOLSA
  • SIGLA_UF_BENEFICIARIO_BOLSA

🔹 Colunas apenas em 2020:
  • CAMPUS
  • CPF_BENEFICIARIO
  • DATA_NASCIMENTO
  • MUNICIPIO
  • MUNICIPIO_BENEFICIARIO
  • RACA_BENEFICIARIO
  • REGIAO_BENEFICIARIO
  • SEXO_BENEFICIARIO
  • UF_BENEFICIARIO

✅ Colunas comuns: 8
  • ANO_CONCESSAO_BOLSA
  • BENEFICIARIO_DEFICIENTE_FISICO
  • CODIGO_EMEC_IES_BOLSA
  • MODALIDADE_ENSINO_BOLSA
  • NOME_CURSO_BOLSA
  • NOME_IES_BOLSA
  • NOME_TURNO_CURSO_BOLSA
  • TIPO_BOLSA

## 📈 4. Estatísticas Descritivas

In [ ]:
# Função para gerar estatísticas descritivas
def estatisticas_descritivas(df, nome):
    if df is not None:
        print(f"\n{'='*30} {nome} {'='*30}")
        
        # Informações gerais
        print(f"\n📊 Informações Gerais:")
        print(df.info())
        
        # Estatísticas para colunas numéricas
        print(f"\n🔢 Estatísticas Numéricas:")
        display(df.describe())
        
        # Estatísticas para colunas categóricas
        print(f"\n📝 Estatísticas Categóricas (primeiras colunas text):")
        colunas_texto = df.select_dtypes(include=['object']).columns[:5]
        if len(colunas_texto) > 0:
            display(df[colunas_texto].describe())

# Gerar estatísticas para ambos os datasets
if sucesso_2019:
    estatisticas_descritivas(df_2019, "ProUni 2019")

if sucesso_2020:
    estatisticas_descritivas(df_2020, "ProUni 2020")

## 🕳️ 5. Análise de Dados Faltantes

In [ ]:
# Função para analisar dados faltantes
def analisar_dados_faltantes(df, nome):
    if df is not None:
        print(f"\n{'='*20} DADOS FALTANTES - {nome} {'='*20}")
        
        # Contagem de valores nulos
        nulos = df.isnull().sum()
        nulos_percent = (nulos / len(df)) * 100
        
        # Criar DataFrame com informações de dados faltantes
        dados_faltantes = pd.DataFrame({
            'Coluna': nulos.index,
            'Valores_Nulos': nulos.values,
            'Percentual': nulos_percent.values
        })
        
        # Filtrar apenas colunas com dados faltantes
        dados_faltantes = dados_faltantes[dados_faltantes['Valores_Nulos'] > 0]
        dados_faltantes = dados_faltantes.sort_values('Percentual', ascending=False)
        
        if len(dados_faltantes) > 0:
            print(f"\n❌ Colunas com dados faltantes:")
            display(dados_faltantes)
            
            # Visualização dos dados faltantes
            if len(dados_faltantes) <= 20:  # Só plotar se não houver muitas colunas
                plt.figure(figsize=(12, 6))
                plt.bar(dados_faltantes['Coluna'], dados_faltantes['Percentual'])
                plt.title(f'Percentual de Dados Faltantes - {nome}')
                plt.xlabel('Colunas')
                plt.ylabel('Percentual (%)')
                plt.xticks(rotation=45, ha='right')
                plt.tight_layout()
                plt.show()
        else:
            print(f"✅ Nenhum dado faltante encontrado!")
        
        return dados_faltantes

# Analisar dados faltantes
if sucesso_2019:
    faltantes_2019 = analisar_dados_faltantes(df_2019, "ProUni 2019")

if sucesso_2020:
    faltantes_2020 = analisar_dados_faltantes(df_2020, "ProUni 2020")

## 📊 6. Visualizações Iniciais

Vamos criar algumas visualizações básicas para entender melhor os dados.

In [ ]:
# Função para criar visualizações básicas
def visualizacoes_basicas(df, nome, ano):
    if df is not None:
        print(f"\n📈 Criando visualizações para {nome}...")
        
        # Tentar identificar colunas relevantes
        colunas = df.columns.tolist()
        
        # Buscar por colunas que possam representar dados importantes
        col_uf = None
        col_modalidade = None
        col_bolsa = None
        col_curso = None
        
        for col in colunas:
            col_lower = col.lower()
            if 'uf' in col_lower or 'estado' in col_lower:
                col_uf = col
            elif 'modalidade' in col_lower:
                col_modalidade = col
            elif 'bolsa' in col_lower or 'tipo' in col_lower:
                col_bolsa = col
            elif 'curso' in col_lower:
                col_curso = col
        
        # Visualização 1: Distribuição por UF (se encontrada)
        if col_uf:
            plt.figure(figsize=(15, 8))
            uf_counts = df[col_uf].value_counts().head(15)
            plt.bar(uf_counts.index, uf_counts.values)
            plt.title(f'Top 15 Estados - {nome}')
            plt.xlabel('UF')
            plt.ylabel('Quantidade de Registros')
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.show()
        
        # Visualização 2: Distribuição por Modalidade (se encontrada)
        if col_modalidade:
            plt.figure(figsize=(10, 6))
            modalidade_counts = df[col_modalidade].value_counts()
            plt.pie(modalidade_counts.values, labels=modalidade_counts.index, autopct='%1.1f%%')
            plt.title(f'Distribuição por Modalidade - {nome}')
            plt.show()
        
        # Visualização 3: Top cursos (se encontrada)
        if col_curso:
            plt.figure(figsize=(15, 8))
            curso_counts = df[col_curso].value_counts().head(20)
            plt.barh(range(len(curso_counts)), curso_counts.values)
            plt.yticks(range(len(curso_counts)), curso_counts.index)
            plt.title(f'Top 20 Cursos - {nome}')
            plt.xlabel('Quantidade de Registros')
            plt.tight_layout()
            plt.show()
        
        print(f"✅ Visualizações criadas para {nome}")
        
        return {
            'col_uf': col_uf,
            'col_modalidade': col_modalidade,
            'col_bolsa': col_bolsa,
            'col_curso': col_curso
        }

# Criar visualizações
if sucesso_2019:
    colunas_2019 = visualizacoes_basicas(df_2019, "ProUni 2019", 2019)

if sucesso_2020:
    colunas_2020 = visualizacoes_basicas(df_2020, "ProUni 2020", 2020)

## 📝 7. Resumo e Próximos Passos

In [ ]:
# Resumo da análise exploratória
print("\n" + "="*60)
print("📋 RESUMO DA ANÁLISE EXPLORATÓRIA DOS DADOS DO PROUNI")
print("="*60)

if sucesso_2019 and sucesso_2020:
    print(f"\n✅ STATUS: Ambos os datasets foram carregados com sucesso")
    print(f"\n📊 DIMENSÕES:")
    print(f"  • ProUni 2019: {df_2019.shape[0]:,} registros x {df_2019.shape[1]} colunas")
    print(f"  • ProUni 2020: {df_2020.shape[0]:,} registros x {df_2020.shape[1]} colunas")
    print(f"  • Total de registros: {df_2019.shape[0] + df_2020.shape[0]:,}")
    
    if 'cols_comuns' in locals():
        print(f"\n🔗 COMPATIBILIDADE:")
        print(f"  • Colunas em comum: {len(cols_comuns)}")
        print(f"  • Estrutura compatível: {'SIM' if len(cols_apenas_2019) == 0 and len(cols_apenas_2020) == 0 else 'NÃO'}")

elif sucesso_2019:
    print(f"\n⚠️  STATUS: Apenas dados de 2019 disponíveis")
    print(f"\n📊 DIMENSÕES:")
    print(f"  • ProUni 2019: {df_2019.shape[0]:,} registros x {df_2019.shape[1]} colunas")

elif sucesso_2020:
    print(f"\n⚠️  STATUS: Apenas dados de 2020 disponíveis")
    print(f"\n📊 DIMENSÕES:")
    print(f"  • ProUni 2020: {df_2020.shape[0]:,} registros x {df_2020.shape[1]} colunas")

else:
    print(f"\n❌ STATUS: Nenhum dataset foi carregado com sucesso")

print(f"\n🚀 PRÓXIMOS PASSOS:")
print(f"\n📋 Fase 2 - Limpeza e Pré-processamento:")
print(f"  1. Padronizar nomes das colunas")
print(f"  2. Tratar dados faltantes identificados")
print(f"  3. Converter tipos de dados adequados (datas, números)")
print(f"  4. Padronizar dados textuais (maiúscula/minúscula)")
print(f"  5. Unificar datasets de diferentes anos")

print(f"\n🎨 Fase 3 - Análise Aprofundada:")
print(f"  1. Análise temporal (evolução 2019-2020)")
print(f"  2. Análise geográfica (distribuição por estado)")
print(f"  3. Análise por curso e instituição")
print(f"  4. Análise de tipos de bolsa")

print(f"\n🎯 Fase 4 - Dashboard:")
print(f"  1. Implementar filtros interativos")
print(f"  2. Criar visualizações dinâmicas")
print(f"  3. Desenvolver interface web com Dash")

print(f"\n" + "="*60)
print(f"🎉 ANÁLISE EXPLORATÓRIA CONCLUÍDA!")
print(f"="*60)